project_id                          = "pristine-dahlia-475318-t9"
domain_name                         = "pristine-dahlia--pristine-dahlia-475318-t9.us-east4.hosted.app"
main_app_cloud_run_service_name     = "nextjs-v16-canary-test"
grpc_callout_cloud_run_service_name = "nextjs-v16-adapter-callout"
region                              = "us-east4"
