project_id                          = "pristine-dahlia-475318-t9"
domain_name                         = "pristine-dahlia.jamesdaniels.net"
main_app_cloud_run_service_name     = "pristine-dahlia"
grpc_callout_cloud_run_service_name = "pristine-dahlia"
region                              = "us-east4"
